---

- name: Install arduino cli
  community.general.homebrew:
    name: arduino-cli

- name: Install arduino ide
  community.general.homebrew_cask:
    name: arduino-ide
  when: arduino_env_ide_install
