---

- name: "Macin'stall"
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.mas
      when: mas_configure
    - role: python_env
    - role: sublime
    - role: osx
      when: osx_configure

  # tasks:
    # - import_tasks: tasks/terminal.yml
