---

- name: "Macin'stall"
  hosts: all

  roles:
    - { role: brew, tags: 'basic'}
    - { role: system, tags: 'basic'}
    - { role: apps, tags: 'graphical'}
    - { role: python-env, tags: 'dev'}
    - { role: go-env, tags: 'dev'}
    - { role: arduino-env, tags: 'electronic'}
