---

- name: "Macin'stall"
  hosts: all

  roles:
    - { role: brew, tags: 'basic'}
    - { role: system, tags: 'basic'}
    - { role: apps, tags: 'graphical'}
    - { role: python_env, tags: 'dev'}
    - { role: go_env, tags: 'dev'}
    - { role: arduino_env, tags: 'electronic'}
