---

- name: "Macin'stall"
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.mac.mas
      when: mas_installed_apps
    - role: python_env
    - role: sublime

  tasks:
    # - import_tasks: tasks/terminal.yml

    # TODO: Use sudo once .osx can be run via root with no user interaction.
    - name: Run .osx dotfiles.
      command: "{{ osx_script }}"
      changed_when: false
