---

- name: Verify
  hosts: all
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Check if arduino-cli installed
      ansible.builtin.shell: arduino-cli version
