---

- name: Converge
  become: true
  hosts: all
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"
  vars:
    python_env_ide_install: false

  roles:
    - role: brew
    - role: python_env
