---

- name: Prepare
  hosts: all
  tasks:
    - name: Install python and other needs
      ansible.builtin.apt:
        pkg:
          - git
          - sudo
          - curl
          - python3
          - python3-setuptools
          - python3-pip
          - python3-yaml
        update_cache: true
