---

- name: Verify
  hosts: all
  environment:
    PATH: "/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Check pip science package
      ansible.builtin.command: pip show pandas
      changed_when: false
    - name: Check pip quantum package
      ansible.builtin.command: pip show qiskit
      changed_when: false
    - name: Check pip test package
      ansible.builtin.command: pip show tox
      changed_when: false
    - name: Check pip coding package
      ansible.builtin.command: pip show direnv
      changed_when: false
