---

- name: Install basic system packages
  community.general.homebrew:
    name: "{{ item }}"
  loop: "{{ system_packages }}"

- name: Install docker
  community.general.homebrew:
    name: docker
  when: system_docker_install

- name: Install anaconda
  community.general.homebrew_cask:
    name: anaconda
  when: system_anaconda_install
