---

- name: Check if Brew installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Install Brew
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL {{ brew_url }})"
  when: not homebrew_check.stat.exists
  changed_when: true
