---

- name: Check if Brew installed
  ansible.builtin.shell: brew --version
  args:
    executable: /bin/bash
  register: homebrew_check
  ignore_errors: true
  changed_when: false

- name: Install Brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL {{ brew_url }})"
  when: homebrew_check.rc != 0
  changed_when: true
