---

- name: Check if Brew installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Install Brew
  ansible.builtin.shell: "curl -fsSL {{ brew_url }}"
  args:
    executable: /bin/bash
  when: not homebrew_check.stat.exists
  changed_when: true
