---

- name: Install video apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ apps_video }}"

- name: Install browser apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ apps_browser }}"

- name: Install coding apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ apps_coding }}"

- name: Install password manager apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ apps_password }}"

- name: Install xtra apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ apps_xtra }}"
