---

- name: Install video apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ video_apps }}"

- name: Install browser apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ browser_apps }}"

- name: Install coding apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ coding_apps }}"

- name: Install password manager apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ password_apps }}"

- name: Install xtra apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ xtra_apps }}"
