---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true

    - name: Install test dependencies.
      package: name=curl state=present

  roles:
    - role: brew
