---

python_env_science_packages:
  - pandas
  - numpy
  - scipy
  - networkx
  - jupyter
  - matplotlib

python_env_quantum_packages:
  - qiskit
  - qiskit-aer
  - qiskit-nature
  - qiskit-finance
  - qiskit-optimization
  - qiskit-machine-learning
  - qiskit-ibm-runtime

python_env_test_packages:
  - tox
  - pytest
  - black
  - pylint
  - coverage
  - pillow
  - testcontainers

python_env_coding_packages:
  - pyyaml
  - nbconvert
  - nbformat
  - direnv
  - streamlit

python_env_xtra_packages: []

python_env_ide_install: true
