---

python_env_science_packages:
  - numpy
  - scipy
  - pandas
  - jupyter
  - networkx
  - matplotlib

python_env_quantum_packages:
  - qiskit
  - qiskit-aer
  - qiskit-nature
  - qiskit-finance
  - qiskit-ibm-runtime
  - qiskit-optimization
  - qiskit-machine-learning

python_env_test_packages:
  - tox
  - black
  - pytest
  - pylint
  - pillow
  - coverage
  - testcontainers

python_env_coding_packages:
  - direnv
  - pyyaml
  - nbformat
  - nbconvert
  - streamlit
  - ansible-lint
  - molecule
  - 'molecule-plugins[docker]'

python_env_xtra_packages: []
