---

- name: Scientific packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ python_env_science_packages }}"

- name: Quantum packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ python_env_quantum_packages }}"

- name: Testing packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ python_env_test_packages }}"

- name: Merge test_packages & xtra_packages vars
  ansible.builtin.set_fact:
    prog_packages: "{{ python_env_test_packages + python_env_xtra_packages }}"

- name: Pagramming + xtra packages
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: "{{ prog_packages }}"

- name: Install pycharm
  community.general.homebrew_cask:
    name: pycharm
  when: python_env_ide_install
