---

- name: Ensure Sublime text user Preferences and theme are set.
  ansible.builtin.copy:
    src: ".osx"
    dest: "{{ osx_path }}"
  mode: '0644'

# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles
  become: true
  ansible.builtin.command: "{{ osx_script }}"
  changed_when: false
