---
name: End2end test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'roles/**'
  workflow_dispatch:

jobs:
  integration:
    name: Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['mac-14', 'macos-13']
    steps:
      - uses: actions/checkout@v4
      - name: Uninstall GitHub Actions built-in Homebrew
        run: ./tests/uninstall-homebrew.sh

      - name: Uninstall GitHub Actions' built-in browser installs
        run: |
          sudo rm -rf /Applications/Firefox.app
          sudo rm -rf /Applications/Google\ Chrome.app
          sudo rm -rf /usr/local/bin/firefox

      - name: Install test dependencies
        run: |
          cp tests/config.yml ./config.yml
          pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy collection install -r requirements.yml

      - name: Test the playbook's syntax
        run: ansible-playbook -i host macinstall.yml --syntax-check

      - name: Test the playbook
        run: ansible-playbook -i host macinstall.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook -i host macinstall.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
