name: Linter

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'roles/**'
      - '**.yml'
      - '**.sh'
  workflow_dispatch:

jobs:
  ansible:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install needs
        run: |
          pip install -r requirements.txt -U
          ansible-galaxy collection install -r requirements.yml --upgrade
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main

  shell:
    name: ShellCheck Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Run shellcheck
        run: shellcheck tests/uninstall-homebrew.sh
