name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'roles/**'
  workflow_dispatch:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        roles: ["python_env"]
    steps:
      - uses: actions/checkout@v4
      - name: Install needs
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          ansible-galaxy install -r requirements.yml
      - name: Run molecule
        run: |
          cd roles/${{ matrix.roles }}
          molecule test
