name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - roles/**'
  workflow_dispatch:

jobs:
  brew:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install needs
        run: |
          pip install -r requirements.txt -U
          ansible-galaxy collection install -r requirements.yml --upgrade
      - name: Run molecule
        run: |
          cd roles/brew
          molecule test
